export interface TeamMember {
  id: string;
  name: string;
  email: string;
  role: string;
  department: string;
  team?: 'Business' | 'Legal' | 'Technical' | 'Marketing' | 'Design';
  reportsTo?: string;
  status: 'active' | 'onLeave' | 'inactive';
  lastLogin?: string;
  joinDate: string;
}

export interface WorkTask {
  id: string;
  title: string;
  assignee: string;
  assigneeRole: string;
  status: 'completed' | 'ongoing' | 'missed' | 'continuous';
  dueDate: string;
  completedDate?: string;
  priority: 'high' | 'medium' | 'low';
  description?: string;
  comments?: string;
  owner?: string;
  coordinationWith?: string;
}

export interface AttendanceRecord {
  date: string;
  email: string;
  loginTime?: string;
  logoutTime?: string;
  status: 'present' | 'absent' | 'onLeave';
}

export interface LeaveRequest {
  id: string;
  employeeName: string;
  employeeEmail: string;
  startDate: string;
  endDate: string;
  reason: string;
  status: 'pending' | 'approved' | 'rejected';
  type: 'vacation' | 'sick' | 'personal';
}

export interface Meeting {
  id: string;
  title: string;
  date: string;
  time: string;
  attendees: string[];
  status: 'scheduled' | 'completed' | 'cancelled';
  minutesUrl?: string;
}

// Team members
export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: '1',
    name: 'Sahith',
    email: 'ceo@nivixpe.com',
    role: 'CEO',
    department: 'Executive',
    team: 'Business',
    status: 'active',
    lastLogin: '2025-05-02 08:55',
    joinDate: '2020-01-15',
  },
  {
    id: '2',
    name: 'Shubham',
    email: 'cto@nivixpe.com',
    role: 'CTO',
    department: 'Technology',
    team: 'Technical',
    reportsTo: 'Sahith',
    status: 'active',
    lastLogin: '2025-05-02 08:50',
    joinDate: '2020-02-01',
  },
  {
    id: '3',
    name: 'Swaraag',
    email: 'cso@nivixpe.com',
    role: 'CSO',
    department: 'Sales & Strategy',
    team: 'Business',
    reportsTo: 'Sahith',
    status: 'active',
    lastLogin: '2025-05-02 08:58',
    joinDate: '2020-03-10',
  },
  {
    id: '4',
    name: 'Abhiram',
    email: 'cmo@nivixpe.com',
    role: 'CMO',
    department: 'Marketing',
    team: 'Marketing',
    reportsTo: 'Sahith',
    status: 'active',
    lastLogin: '2025-05-02 09:02',
    joinDate: '2020-04-15',
  },
  {
    id: '5',
    name: 'Ujjwal',
    email: 'dcso@nivixpe.com',
    role: 'DCSO',
    department: 'Deputy Sales & Strategy',
    team: 'Business',
    reportsTo: 'Swaraag',
    status: 'active',
    lastLogin: '2025-05-02 09:10',
    joinDate: '2021-01-20',
  },
  {
    id: '6',
    name: 'Bhavika',
    email: 'dcmo@nivixpe.com',
    role: 'DCMO',
    department: 'Deputy Marketing',
    team: 'Marketing',
    reportsTo: 'Abhiram',
    status: 'active',
    lastLogin: '2025-05-02 09:05',
    joinDate: '2021-02-10',
  },
  {
    id: '7',
    name: 'Siddharatha',
    email: 'coo@nivixpe.com',
    role: 'COO',
    department: 'Operations',
    team: 'Business',
    reportsTo: 'Sahith',
    status: 'active',
    lastLogin: '2025-05-02 08:52',
    joinDate: '2020-05-01',
  },
  {
    id: '8',
    name: 'Aradhya',
    email: 'designer1@nivixpe.com',
    role: 'Designer',
    department: 'Design',
    team: 'Design',
    reportsTo: 'Shubham',
    status: 'active',
    lastLogin: '2025-05-02 09:15',
    joinDate: '2021-06-15',
  },
  {
    id: '9',
    name: 'Rudra Sahu',
    email: 'designer2@nivixpe.com',
    role: 'Designer',
    department: 'Design',
    team: 'Design',
    reportsTo: 'Shubham',
    status: 'active',
    lastLogin: '2025-05-02 09:20',
    joinDate: '2021-07-01',
  },
  {
    id: '10',
    name: 'Kashish',
    email: 'legal@nivixpe.com',
    role: 'Legal',
    department: 'Legal & Compliance',
    team: 'Legal',
    reportsTo: 'Sahith',
    status: 'active',
    lastLogin: '2025-05-02 09:00',
    joinDate: '2020-08-01',
  },
  {
    id: '11',
    name: 'Ngan Nguyen',
    email: 'developer1@nivixpe.com',
    role: 'Developer 1',
    department: 'Technology',
    team: 'Technical',
    reportsTo: 'Shubham',
    status: 'active',
    lastLogin: '2025-05-02 09:25',
    joinDate: '2025-05-01',
  },
  {
    id: '12',
    name: 'Huy Ho',
    email: 'developer2@nivixpe.com',
    role: 'Developer 2',
    department: 'Technology',
    team: 'Technical',
    reportsTo: 'Shubham',
    status: 'active',
    lastLogin: '2025-05-02 09:30',
    joinDate: '2025-05-01',
  },
  {
    id: '13',
    name: 'Vinisha',
    email: 'legal2@nivixpe.com',
    role: 'Legal Intern',
    department: 'Legal & Compliance',
    team: 'Legal',
    reportsTo: 'Sahith',
    status: 'active',
    lastLogin: '2025-05-15 09:00',
    joinDate: '2025-05-15',
  },
  {
    id: '14',
    name: 'Nithin Sureddy',
    email: 'developer3@nivix.com',
    role: 'Developer 3',
    department: 'Technology',
    team: 'Technical',
    reportsTo: 'Shubham',
    status: 'active',
    lastLogin: '2025-05-02 09:35',
    joinDate: '2025-05-01',
  },
];

// Daily work tasks
export const WORK_TASKS: WorkTask[] = [
  // Business Team Work (Swaraag)
  {
    id: 'bt1',
    title: 'Business Model Canvas',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'completed',
    dueDate: '2025-04-15',
    completedDate: '2025-04-15',
    priority: 'high',
    owner: 'Swaraag',
    comments: 'Completed and approved',
  },
  {
    id: 'bt2',
    title: 'Awareness Campaign',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'completed',
    dueDate: '2025-04-18',
    completedDate: '2025-04-18',
    priority: 'high',
    owner: 'Swaraag',
    comments: 'Campaign launched successfully',
  },
  {
    id: 'bt3',
    title: 'Traction Control',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'completed',
    dueDate: '2025-04-20',
    completedDate: '2025-04-20',
    priority: 'high',
    owner: 'Swaraag',
    comments: 'Metrics established',
  },
  {
    id: 'bt4',
    title: 'Market Opportunity (TAM, SAM, SOM)',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'completed',
    dueDate: '2025-04-22',
    completedDate: '2025-04-22',
    priority: 'high',
    owner: 'Swaraag',
    comments: 'Market analysis completed',
  },
  {
    id: 'bt5',
    title: 'Pitch Deck',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'completed',
    dueDate: '2025-04-25',
    completedDate: '2025-04-25',
    priority: 'high',
    owner: 'Swaraag',
    comments: 'Final version approved',
  },
  {
    id: 'bt6',
    title: 'Company Valuation',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'completed',
    dueDate: '2025-04-26',
    completedDate: '2025-04-26',
    priority: 'high',
    owner: 'Swaraag',
    coordinationWith: 'Ujjwal',
    comments: 'Completed in coordination with Ujjwal',
  },
  {
    id: 'bt7',
    title: '1 Year Plan',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'completed',
    dueDate: '2025-04-28',
    completedDate: '2025-04-28',
    priority: 'high',
    owner: 'Swaraag',
    comments: 'Strategic plan finalized',
  },
  {
    id: 'bt8',
    title: 'Allocation of Funds - Initial',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'completed',
    dueDate: '2025-04-29',
    completedDate: '2025-04-29',
    priority: 'high',
    owner: 'Swaraag',
    coordinationWith: 'Sahith',
    comments: 'Completed in coordination with Sahith',
  },
  {
    id: 'bt9',
    title: 'NIVIXPE Report',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'completed',
    dueDate: '2025-04-30',
    completedDate: '2025-04-30',
    priority: 'high',
    owner: 'Swaraag',
    coordinationWith: 'Sahith',
    comments: 'Completed in coordination with Sahith',
  },
  {
    id: 'bt10',
    title: 'Business Note',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'completed',
    dueDate: '2025-05-01',
    completedDate: '2025-05-01',
    priority: 'high',
    owner: 'Swaraag',
    coordinationWith: 'Sahith',
    comments: 'Completed in coordination with Sahith',
  },
  {
    id: 'bt11',
    title: 'Company Policies',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'ongoing',
    dueDate: '2025-05-10',
    priority: 'high',
    owner: 'Swaraag',
    coordinationWith: 'Kashish',
    comments: 'In coordination with Kashish',
  },
  {
    id: 'bt12',
    title: 'Business Strategy',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'ongoing',
    dueDate: '2025-05-15',
    priority: 'high',
    owner: 'Swaraag',
    comments: 'In Review',
  },
  {
    id: 'bt13',
    title: 'Revenue Strategy',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'ongoing',
    dueDate: '2025-05-20',
    priority: 'high',
    owner: 'Swaraag',
    comments: 'Currently in discussion',
  },
  {
    id: 'bt14',
    title: 'Investor Based Plan (Wolf Company)',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'ongoing',
    dueDate: '2025-05-25',
    priority: 'high',
    owner: 'Swaraag',
    comments: 'In discussions',
  },
  {
    id: 'bt15',
    title: 'Monthly Reports',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'continuous',
    dueDate: 'Ongoing',
    priority: 'high',
    owner: 'Swaraag',
    coordinationWith: 'Sahith',
    comments: 'Continuous - In coordination with Sahith',
  },
  {
    id: 'bt16',
    title: 'IFSCA Discussions',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'ongoing',
    dueDate: '2025-06-01',
    priority: 'high',
    owner: 'Swaraag',
    coordinationWith: 'Sahith, Ujjwal',
    comments: 'In coordination with Sahith and Ujjwal',
  },
  {
    id: 'bt17',
    title: 'Regulatory Follow Ups',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'continuous',
    dueDate: 'Ongoing',
    priority: 'high',
    owner: 'Swaraag',
    coordinationWith: 'Kashish',
    comments: 'Continuous - In coordination with Kashish',
  },
  {
    id: 'bt18',
    title: 'Investor Discussion and Partnerships',
    assignee: 'Swaraag',
    assigneeRole: 'CSO',
    status: 'ongoing',
    dueDate: '2025-06-15',
    priority: 'high',
    owner: 'Swaraag',
    coordinationWith: 'Sahith',
    comments: 'In coordination with Sahith',
  },

  // Ujjwal Work Tracker
  {
    id: 'uj1',
    title: 'Final Valuation Analysis',
    assignee: 'Ujjwal',
    assigneeRole: 'DCSO',
    status: 'completed',
    dueDate: '2025-04-26',
    completedDate: '2025-04-26',
    priority: 'high',
    owner: 'Ujjwal',
    coordinationWith: 'Swaraag',
    comments: 'Completed in coordination with Swaraag',
  },
  {
    id: 'uj2',
    title: 'Investors LinkedIn Analysis',
    assignee: 'Ujjwal',
    assigneeRole: 'DCSO',
    status: 'completed',
    dueDate: '2025-04-20',
    completedDate: '2025-04-20',
    priority: 'medium',
    owner: 'Ujjwal',
    comments: 'Completed',
  },
  {
    id: 'uj3',
    title: 'Short Intro Script',
    assignee: 'Ujjwal',
    assigneeRole: 'DCSO',
    status: 'completed',
    dueDate: '2025-04-22',
    completedDate: '2025-04-22',
    priority: 'medium',
    owner: 'Ujjwal',
    comments: 'Completed',
  },
  {
    id: 'uj4',
    title: '75 Lakhs Budget Allocation (12 months)',
    assignee: 'Ujjwal',
    assigneeRole: 'DCSO',
    status: 'completed',
    dueDate: '2025-04-29',
    completedDate: '2025-04-29',
    priority: 'high',
    owner: 'Ujjwal',
    coordinationWith: 'Sahith',
    comments: 'Completed in coordination with Sahith',
  },
  {
    id: 'uj5',
    title: 'Revolut Full Detailed Analysis',
    assignee: 'Ujjwal',
    assigneeRole: 'DCSO',
    status: 'completed',
    dueDate: '2025-04-24',
    completedDate: '2025-04-24',
    priority: 'medium',
    owner: 'Ujjwal',
    comments: 'Completed',
  },
  {
    id: 'uj6',
    title: 'Currency Valuation Comparison',
    assignee: 'Ujjwal',
    assigneeRole: 'DCSO',
    status: 'completed',
    dueDate: '2025-04-25',
    completedDate: '2025-04-25',
    priority: 'medium',
    owner: 'Ujjwal',
    comments: 'Completed',
  },
  {
    id: 'uj7',
    title: 'Slice Full Detailed Analysis',
    assignee: 'Ujjwal',
    assigneeRole: 'DCSO',
    status: 'completed',
    dueDate: '2025-04-27',
    completedDate: '2025-04-27',
    priority: 'medium',
    owner: 'Ujjwal',
    comments: 'Completed',
  },
  {
    id: 'uj8',
    title: 'Difference in Strategy in Marketing',
    assignee: 'Ujjwal',
    assigneeRole: 'DCSO',
    status: 'completed',
    dueDate: '2025-04-28',
    completedDate: '2025-04-28',
    priority: 'medium',
    owner: 'Ujjwal',
    comments: 'Completed',
  },
  {
    id: 'uj9',
    title: 'Customer Switching Behaviour',
    assignee: 'Ujjwal',
    assigneeRole: 'DCSO',
    status: 'ongoing',
    dueDate: '2025-05-10',
    priority: 'high',
    owner: 'Ujjwal',
    coordinationWith: 'Sahith',
    comments: 'In coordination with Sahith',
  },
  {
    id: 'uj10',
    title: 'IFSCA Discussions',
    assignee: 'Ujjwal',
    assigneeRole: 'DCSO',
    status: 'ongoing',
    dueDate: '2025-06-01',
    priority: 'high',
    owner: 'Ujjwal',
    coordinationWith: 'Sahith, Swaraag',
    comments: 'In coordination with Sahith and Swaraag',
  },

  // CEO Tasks
  {
    id: 'ceo1',
    title: 'Strategic Planning & Board Meeting',
    assignee: 'Sahith',
    assigneeRole: 'CEO',
    status: 'completed',
    dueDate: '2025-05-02',
    completedDate: '2025-05-02 10:30',
    priority: 'high',
    owner: 'Sahith',
    comments: 'Q1 review completed',
  },
  {
    id: 'ceo2',
    title: 'Business Team Oversight',
    assignee: 'Sahith',
    assigneeRole: 'CEO',
    status: 'continuous',
    dueDate: 'Ongoing',
    priority: 'high',
    owner: 'Sahith',
    comments: 'Continuous oversight of Swaraag and Business Team',
  },

  // COO Tasks
  {
    id: 'coo1',
    title: 'Operations Streamlining',
    assignee: 'Siddharatha',
    assigneeRole: 'COO',
    status: 'ongoing',
    dueDate: '2025-05-08',
    priority: 'high',
    owner: 'Siddharatha',
    comments: 'Optimizing operational workflows',
  },
  {
    id: 'coo2',
    title: 'Cross-Team Coordination',
    assignee: 'Siddharatha',
    assigneeRole: 'COO',
    status: 'continuous',
    dueDate: 'Ongoing',
    priority: 'high',
    owner: 'Siddharatha',
    comments: 'Daily coordination across all teams',
  },

  // Legal Team Tasks (Kashish)
  {
    id: 'legal1',
    title: 'IFSCA Compliance Framework',
    assignee: 'Kashish',
    assigneeRole: 'Legal',
    status: 'ongoing',
    dueDate: '2025-05-20',
    priority: 'high',
    owner: 'Kashish',
    comments: 'Regulatory compliance documentation',
  },
  {
    id: 'legal2',
    title: 'AML and Risk Framework',
    assignee: 'Kashish',
    assigneeRole: 'Legal',
    status: 'ongoing',
    dueDate: '2025-05-25',
    priority: 'high',
    owner: 'Kashish',
    comments: 'Anti-money laundering policies',
  },
  {
    id: 'legal3',
    title: 'DPDP Act Readiness',
    assignee: 'Kashish',
    assigneeRole: 'Legal',
    status: 'completed',
    dueDate: '2025-04-30',
    completedDate: '2025-04-30',
    priority: 'high',
    owner: 'Kashish',
    comments: 'Data protection compliance completed',
  },
  {
    id: 'legal4',
    title: 'Company Policies Documentation',
    assignee: 'Kashish',
    assigneeRole: 'Legal',
    status: 'ongoing',
    dueDate: '2025-05-10',
    priority: 'high',
    owner: 'Kashish',
    coordinationWith: 'Swaraag',
    comments: 'In coordination with Swaraag',
  },
  {
    id: 'legal5',
    title: 'NDA and Partner Agreements',
    assignee: 'Kashish',
    assigneeRole: 'Legal',
    status: 'completed',
    dueDate: '2025-04-25',
    completedDate: '2025-04-25',
    priority: 'medium',
    owner: 'Kashish',
    comments: 'Standard templates finalized',
  },
  {
    id: 'legal6',
    title: 'Blockchain Governance Framework',
    assignee: 'Kashish',
    assigneeRole: 'Legal',
    status: 'ongoing',
    dueDate: '2025-06-01',
    priority: 'high',
    owner: 'Kashish',
    comments: 'Legal framework for blockchain operations',
  },
  {
    id: 'legal7',
    title: 'Regulatory Follow Ups',
    assignee: 'Kashish',
    assigneeRole: 'Legal',
    status: 'continuous',
    dueDate: 'Ongoing',
    priority: 'high',
    owner: 'Kashish',
    coordinationWith: 'Swaraag',
    comments: 'Continuous regulatory monitoring',
  },

  // Marketing Team Tasks (Abhiram - CMO)
  {
    id: 'cmo1',
    title: 'Brand Strategy Development',
    assignee: 'Abhiram',
    assigneeRole: 'CMO',
    status: 'completed',
    dueDate: '2025-04-20',
    completedDate: '2025-04-20',
    priority: 'high',
    owner: 'Abhiram',
    comments: 'Brand positioning finalized',
  },
  {
    id: 'cmo2',
    title: 'Marketing Campaign Planning',
    assignee: 'Abhiram',
    assigneeRole: 'CMO',
    status: 'ongoing',
    dueDate: '2025-05-15',
    priority: 'high',
    owner: 'Abhiram',
    comments: 'Q2 campaign strategy',
  },
  {
    id: 'cmo3',
    title: 'Digital Marketing Strategy',
    assignee: 'Abhiram',
    assigneeRole: 'CMO',
    status: 'ongoing',
    dueDate: '2025-05-20',
    priority: 'high',
    owner: 'Abhiram',
    coordinationWith: 'Bhavika',
    comments: 'Social media and content strategy',
  },
  {
    id: 'cmo4',
    title: 'Customer Acquisition Plan',
    assignee: 'Abhiram',
    assigneeRole: 'CMO',
    status: 'ongoing',
    dueDate: '2025-05-25',
    priority: 'high',
    owner: 'Abhiram',
    comments: 'Growth marketing initiatives',
  },
  {
    id: 'cmo5',
    title: 'Marketing Budget Allocation',
    assignee: 'Abhiram',
    assigneeRole: 'CMO',
    status: 'completed',
    dueDate: '2025-04-28',
    completedDate: '2025-04-28',
    priority: 'high',
    owner: 'Abhiram',
    coordinationWith: 'Sahith',
    comments: 'Budget approved by CEO',
  },

  // Marketing Team Tasks (Bhavika - DCMO)
  {
    id: 'dcmo1',
    title: 'Content Marketing Strategy',
    assignee: 'Bhavika',
    assigneeRole: 'DCMO',
    status: 'ongoing',
    dueDate: '2025-05-12',
    priority: 'medium',
    owner: 'Bhavika',
    comments: 'Blog and social media content plan',
  },
  {
    id: 'dcmo2',
    title: 'Social Media Management',
    assignee: 'Bhavika',
    assigneeRole: 'DCMO',
    status: 'continuous',
    dueDate: 'Ongoing',
    priority: 'medium',
    owner: 'Bhavika',
    comments: 'Daily social media operations',
  },
  {
    id: 'dcmo3',
    title: 'Email Marketing Campaigns',
    assignee: 'Bhavika',
    assigneeRole: 'DCMO',
    status: 'completed',
    dueDate: '2025-04-30',
    completedDate: '2025-04-30',
    priority: 'medium',
    owner: 'Bhavika',
    comments: 'Newsletter templates created',
  },
  {
    id: 'dcmo4',
    title: 'Marketing Analytics Setup',
    assignee: 'Bhavika',
    assigneeRole: 'DCMO',
    status: 'ongoing',
    dueDate: '2025-05-18',
    priority: 'medium',
    owner: 'Bhavika',
    coordinationWith: 'Abhiram',
    comments: 'Tracking and reporting dashboard',
  },

  // Design Team Tasks
  {
    id: 'design1',
    title: 'UI/UX Design System',
    assignee: 'Aradhya',
    assigneeRole: 'Designer',
    status: 'ongoing',
    dueDate: '2025-05-15',
    priority: 'high',
    owner: 'Aradhya',
    comments: 'Component library development',
  },
  {
    id: 'design2',
    title: 'Brand Identity Design',
    assignee: 'Aradhya',
    assigneeRole: 'Designer',
    status: 'completed',
    dueDate: '2025-04-22',
    completedDate: '2025-04-22',
    priority: 'high',
    owner: 'Aradhya',
    comments: 'Logo and brand guidelines finalized',
  },
  {
    id: 'design3',
    title: 'Marketing Collateral Design',
    assignee: 'Rudra Sahu',
    assigneeRole: 'Designer',
    status: 'ongoing',
    dueDate: '2025-05-10',
    priority: 'medium',
    owner: 'Rudra Sahu',
    coordinationWith: 'Abhiram',
    comments: 'Brochures and presentation templates',
  },
  {
    id: 'design4',
    title: 'Website Design Updates',
    assignee: 'Rudra Sahu',
    assigneeRole: 'Designer',
    status: 'ongoing',
    dueDate: '2025-05-20',
    priority: 'medium',
    owner: 'Rudra Sahu',
    comments: 'Landing page redesign',
  },
];

// Daily attendance
export const ATTENDANCE_RECORDS: AttendanceRecord[] = [
  {
    date: '2025-05-02',
    email: 'ceo@nivixpe.com',
    loginTime: '08:55',
    logoutTime: '19:00',
    status: 'present',
  },
  {
    date: '2025-05-02',
    email: 'cto@nivixpe.com',
    loginTime: '08:50',
    logoutTime: '18:45',
    status: 'present',
  },
  {
    date: '2025-05-02',
    email: 'cso@nivixpe.com',
    loginTime: '08:58',
    logoutTime: '18:30',
    status: 'present',
  },
  {
    date: '2025-05-02',
    email: 'cmo@nivixpe.com',
    loginTime: '09:02',
    logoutTime: '18:15',
    status: 'present',
  },
  {
    date: '2025-05-02',
    email: 'dcso@nivixpe.com',
    loginTime: '09:10',
    logoutTime: '18:20',
    status: 'present',
  },
  {
    date: '2025-05-02',
    email: 'dcmo@nivixpe.com',
    loginTime: '09:05',
    logoutTime: '18:00',
    status: 'present',
  },
  {
    date: '2025-05-02',
    email: 'coo@nivixpe.com',
    loginTime: '08:52',
    logoutTime: '18:30',
    status: 'present',
  },
  {
    date: '2025-05-02',
    email: 'designer1@nivixpe.com',
    loginTime: '09:15',
    logoutTime: '18:00',
    status: 'present',
  },
  {
    date: '2025-05-02',
    email: 'designer2@nivixpe.com',
    loginTime: '09:20',
    logoutTime: '18:00',
    status: 'present',
  },
  {
    date: '2025-05-02',
    email: 'legal@nivixpe.com',
    loginTime: '09:00',
    logoutTime: '18:30',
    status: 'present',
  },
  {
    date: '2025-05-02',
    email: 'developer1@nivixpe.com',
    loginTime: '09:25',
    logoutTime: '18:00',
    status: 'present',
  },
  {
    date: '2025-05-02',
    email: 'developer2@nivixpe.com',
    loginTime: '09:30',
    logoutTime: '18:00',
    status: 'present',
  },
  {
    date: '2025-05-02',
    email: 'developer3@nivix.com',
    loginTime: '09:35',
    logoutTime: '18:00',
    status: 'present',
  },
];

// Leave requests
export const LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: '1',
    employeeName: 'Abhiram',
    employeeEmail: 'cmo@nivixpe.com',
    startDate: '2025-05-10',
    endDate: '2025-05-11',
    reason: 'Personal work',
    status: 'pending',
    type: 'personal',
  },
  {
    id: '2',
    employeeName: 'Bhavika',
    employeeEmail: 'dcmo@nivixpe.com',
    startDate: '2025-05-15',
    endDate: '2025-05-16',
    reason: 'Medical appointment',
    status: 'approved',
    type: 'sick',
  },
  {
    id: '3',
    employeeName: 'Aradhya',
    employeeEmail: 'designer1@nivixpe.com',
    startDate: '2025-06-01',
    endDate: '2025-06-05',
    reason: 'Annual leave',
    status: 'pending',
    type: 'vacation',
  },
];

// Meetings
export const MEETINGS: Meeting[] = [
  {
    id: '1',
    title: 'CEO Strategic Review - All Departments',
    date: '2025-05-02',
    time: '10:00',
    attendees: ['Sahith', 'Shubham', 'Siddharatha', 'Swaraag', 'Kashish'],
    status: 'completed',
    minutesUrl: '/documents/strategic-review.pdf',
  },
  {
    id: '2',
    title: 'Business Team Sync',
    date: '2025-05-02',
    time: '11:30',
    attendees: ['Sahith', 'Swaraag', 'Ujjwal', 'Siddharatha'],
    status: 'completed',
    minutesUrl: '/documents/business-team-minutes.pdf',
  },
  {
    id: '3',
    title: 'Tech Team Standup',
    date: '2025-05-02',
    time: '14:00',
    attendees: ['Shubham', 'Aradhya', 'Rudra Sahu'],
    status: 'completed',
  },
  {
    id: '4',
    title: 'IFSCA Discussion',
    date: '2025-05-03',
    time: '11:00',
    attendees: ['Sahith', 'Swaraag', 'Ujjwal', 'Kashish'],
    status: 'scheduled',
  },
  {
    id: '5',
    title: 'Marketing Strategy Review',
    date: '2025-05-03',
    time: '15:00',
    attendees: ['Sahith', 'Abhiram', 'Bhavika'],
    status: 'scheduled',
  },
];
